version: "3.4"
services:
     postgres:
          image: postgres
          environment:
               POSTGRES_DB: ${POSTGRES_DB}
               POSTGRES_USER: ${POSTGRES_USER}
               POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          ports:
               - "${POSTGRES_PORT}:${POSTGRES_PORT}"
     
     mongo:
          image: mongo
          environment:
               MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
               MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
               MONGO_INITDB_DATABASE: ${MONGODB_DB}
          
          ports: 
               - "${MONGODB_PORT}:${MONGODB_PORT}"
     redis:
          image: "redis:alpine"
          ports:
               - "${REDIS_PORT}:${REDIS_PORT}"
     celery:
          environment:
               REDIS_HOST: ${REDIS_HOST}
               REDIS_PORT: ${REDIS_PORT}
               REDIS_DB: ${REDIS_DB}
          build: .
          command:  sh -c "celery -A miio_challenge worker -l info"
          depends_on:
               - postgres
               - redis
               - mongo
          image: app-image
          volumes: 
               - .:/code
          
          restart: on-failure

     web:
          build: .
          command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
          volumes: 
               - .:/code
          ports:
               - "${DJANGO_PORT}:${DJANGO_PORT}"
          depends_on:
               - postgres
               - mongo
               - redis
               - celery
          restart: on-failure
