# Generated by Django 3.1.4 on 2020-12-19 21:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import regularPlan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tar_included', models.BooleanField()),
                ('subscription', models.FloatField(validators=[regularPlan.models.validate_bigger_than_zero])),
                ('cycle', models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly')])),
                ('type', models.IntegerField(choices=[(1, 'Bi-Time'), (2, 'Tri-Time'), (3, 'Simple')])),
                ('offer_iva', models.BooleanField()),
                ('off_peak_price', models.FloatField(validators=[regularPlan.models.validate_bigger_than_zero])),
                ('peak_price', models.FloatField(validators=[regularPlan.models.validate_bigger_than_zero])),
                ('unit', models.IntegerField(choices=[(1, 'Kwh'), (2, 'Min')])),
                ('valid', models.BooleanField()),
                ('publish', models.BooleanField()),
                ('vat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
